[/]
default='a06e027e-e4f7-4ace-ba08-33e112f2b358'
list=['a06e027e-e4f7-4ace-ba08-33e112f2b358', 'ffcd7415-47e4-461e-978c-f3d320bb7081']

[:a06e027e-e4f7-4ace-ba08-33e112f2b358]
background-color='rgb(34,45,50)'
bold-color='#F2F2F2F2F2F2'
bold-color-same-as-fg=true
font='Droid Sans Mono for Powerline 12'
foreground-color='#d9d9e6e6f2f2'
palette=['#0a0a0a0a0a0a', '#abab8f8f7474', '#7474abab8f8f', '#8f8fabab7474', '#8f8f7474abab', '#abab74748f8f', '#74748f8fabab', '#F2F2F2F2F2F2', '#5D5D5D5D5D5D', '#FFFF1D1D6262', '#9c9cc3c3afaf', '#FFFFD0D00A0A', '#afaf9c9cc3c3', '#FFFF1D1D6262', '#4B4BB8B8FDFD', '#A0A02020F0F0']
scrollbar-policy='never'
use-system-font=false
use-theme-background=false
use-theme-colors=false
visible-name='Gorgeous'

[:ffcd7415-47e4-461e-978c-f3d320bb7081]
allow-bold=true
background-color='#2D2D2D2D2D2D'
bold-color='#D4D4D4D4D4D4'
bold-color-same-as-fg=true
font='Droid Sans Mono for Powerline 12'
foreground-color='#D4D4D4D4D4D4'
palette=['#646464646464', '#F5F58E8E8E8E', '#A9A9D3D3ABAB', '#FEFED3D37E7E', '#7A7AABABD4D4', '#D6D6ADADD5D5', '#7979D4D4D5D5', '#D4D4D4D4D4D4', '#646464646464', '#F5F58E8E8E8E', '#A9A9D3D3ABAB', '#FEFED3D37E7E', '#7A7AABABD4D4', '#D6D6ADADD5D5', '#7979D4D4D5D5', '#D4D4D4D4D4D4']
scrollbar-policy='never'
use-system-font=false
use-theme-background=false
use-theme-colors=false
visible-name='Chalk'
